FROM registry.access.redhat.com/ubi8/openjdk-21:latest

ENV LANGUAGE='en' LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# Copy the built JAR
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/quarkus-run.jar

EXPOSE 8080
USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT exec java $JAVA_OPTS -jar $JAVA_APP_JAR